### PR TITLE
Add e2e tests, move CI to GA and deps upgrades

### PR DESCRIPTION
**Pull request by jraddaoui**
- Add e2e tests with Cypress and Github Actions:
  - Start integration tests with Cypress, add minor spec to test a folder
    creation with a manual DIP upload and its deletion.
  - Add Django management command to create a superuser without
    user interaction (could be removed in Django 3.x).
  - Add integration tests Github Actions workflow. Setups a production
    like instance and runs the tests over Chrome, Firefox and Electron.
  - Update testing notes in readme file.
- Move unit tests and syntax checks to Github Actions.
- Upgrade dependencies:
  - Update pre-commit hooks.
  - Upgrade pip dependencies except Celery and Django.
  - Upgrade npm dependencies and Remove popper.js and
    use bundled version from Bootstrap.
- Update Docker environment:
  - Improve cache management of Dockerfile layers.
  - Limit containers access to Docker host.
  - Update .dockerignore.
  - Upgrade Redis and Elasticsearch Docker images.
- Make messages.

### CODE REVIEW

**Comment by jraddaoui** [comment]
Hi @sevein, I still need to clean this up a bit, but I'd appreciate your insights if you have some time.

**Comment by jraddaoui** [comment]
Clean-ups done.

**Review by sevein — APPROVED** [review]
Neat! Cypress is so cool too.

**Comment by jraddaoui** [comment]
Thanks @sevein!

**Pull request merged**
